/**
 * Client-safe author profile navigation helper.
 *
 * The author-profiles map is a static snapshot of
 * `lib/articles/config/author-profiles.json` (generated by
 * `scripts/generate-author-profiles.ts` from `people.yml` + alias YAMLs).
 * The literal is inlined here (rather than `import ... from "./author-profiles.json"`)
 * because importing a `.json` module from a client subgraph forces Turbopack to
 * bundle that subgraph eagerly, which surfaces a pre-existing `node:fs` conflict
 * in `lib/markdown/people.ts` (`resolvePerson` uses `readFileSync`). Inlining the
 * data keeps this module a pure-ESM object literal with zero transitive
 * filesystem dependencies.
 *
 * Re-sync: print `author-profiles.json` with tsx and replace the literal below
 * whenever `people.yml` or the alias YAMLs change.
 */

export const authorProfilesMap: Readonly<Record<string, string>> = {
  "4rcadia": "Arcadi4",
  "BFladderbean": "BFladderbeanawa",
  "Fallen_Breath": "Fallen_Breath",
  "Molforte": "Molforte",
  "Petris": "Petris",
  "Ryan100c": "hotpad100c",
  "Twisuki": "Twisuki",
  "XJH_Jorhai": "XJH_Jorhai",
  "tanh_Heng": "tanhHeng",
  "void": "void",
  "xhbsh": "SDU-Little-River",
  "yuhan2680": "yuhan2680",
}

/**
 * Navigable canonical author handles (snapshot of `getUniqueAuthors()` from
 * `lib/articles/person-resolver.ts`). The author detail route at
 * `app/[locale]/(public)/authors/[handle]/page.tsx` validates handles via
 * `getUniqueAuthors().includes(handle)` and 404s otherwise, so a people-key
 * whose canonical handle is not in this set must NOT render as a link
 * (otherwise every `@void`, `@4rcadia`, `@Fallen_Breath` mention would link
 * to a 404 destination).
 *
 * Re-sync: print `getUniqueAuthors()` with tsx and replace the list below
 * whenever `getUniqueAuthors()` changes
 * (new contributor publishes first article, author becomes maintainer, etc.).
 */
const NAVIGABLE_AUTHOR_HANDLES: ReadonlySet<string> = new Set([
  "BFladderbeanawa",
  "Gudu-Z",
  "hotpad100c",
  "Huang He",
  "jslskd",
  "Molforte",
  "MorningMC",
  "Petris",
  "RoyanAB",
  "SDU-Little-River",
  "tanhHeng",
  "Twisuki",
])

/**
 * Returns the canonical manifest handle for `peopleKey` if that handle has a
 * live author profile page, otherwise `null`. A `null` result means the
 * mention should keep the non-navigating button behavior.
 */
export function getAuthorProfileHandle(peopleKey: string): string | null {
  const canonical = authorProfilesMap[peopleKey]
  if (!canonical) return null
  if (!NAVIGABLE_AUTHOR_HANDLES.has(canonical)) return null
  return canonical
}

/**
 * True when `peopleKey` resolves to an author with a profile page and the
 * mention should render as a locale-aware link instead of a toggle button.
 */
export function isNavigableAuthor(peopleKey: string): boolean {
  return getAuthorProfileHandle(peopleKey) !== null
}