import { readFileSync, writeFileSync, existsSync } from "node:fs"
import { join } from "node:path"
import { load as yamlLoad } from "js-yaml"
import type { ArticleEntry } from "@/lib/articles/manifest"

const CONFIG_DIR = join(process.cwd(), "lib", "articles", "config")
const PEOPLE_PATH = join(CONFIG_DIR, "people.yml")
const ALIASES_PATH = join(CONFIG_DIR, "authors-alias.yml")
const ALIAS_OVERRIDES_PATH = join(CONFIG_DIR, "author-alias-overrides.yml")
const MAINTAINERS_PATH = join(CONFIG_DIR, "maintainers.yml")
const MANIFEST_PATH = join(process.cwd(), "data", "manifest.json")
const PROFILES_JSON_PATH = join(CONFIG_DIR, "author-profiles.json")
const PROFILES_TS_PATH = join(CONFIG_DIR, "author-profiles.ts")
const PEOPLE_TS_PATH = join(CONFIG_DIR, "people-data.ts")

type AliasMap = Record<string, string[]>
type PeopleMap = Record<string, unknown>

function loadYaml<T>(filePath: string): T | null {
  if (!existsSync(filePath)) return null
  return yamlLoad(readFileSync(filePath, "utf-8")) as T
}

function buildAliasResolver(
  auto: AliasMap | null,
  overrides: AliasMap | null
): Map<string, string> {
  const map = new Map<string, string>()
  const merge = (entries: AliasMap): void => {
    for (const [canonical, aliases] of Object.entries(entries)) {
      map.set(canonical.toLowerCase(), canonical)
      for (const alias of aliases) {
        map.set(alias.toLowerCase(), canonical)
      }
    }
  }
  if (auto) merge(auto)
  if (overrides) merge(overrides)
  return map
}

function renderAuthorProfiles(
  profiles: Record<string, string>,
  authors: Set<string>
): string {
  const navigable = Object.fromEntries(
    Object.entries(profiles).filter(([, handle]) =>
      authors.has(handle.toLowerCase())
    )
  )

  return `// Generated by scripts/generate-author-profiles.ts. Do not edit.
export const authorProfilesMap: Readonly<Record<string, string>> = ${JSON.stringify(navigable, null, 2)}

export function getAuthorProfileHandle(peopleKey: string): string | null {
  return authorProfilesMap[peopleKey] ?? null
}
`
}

function renderPeopleData(people: PeopleMap): string {
  return `// Generated from people.yml by scripts/generate-author-profiles.ts. Do not edit.
export type PeopleEntry = {
  name: string
  description?: string
  profile?: string
  email?: string
  social?: {
    github?: string
    bilibili?: string
    twitter?: string
    website?: string
    custom?: Array<{ label: string; url: string }>
  }
}

export type ResolvedPerson = {
  key: string
  name: string
  description: string | null
  profile: string | null
  email: string | null
  social: NonNullable<PeopleEntry["social"]>
  isFallback: boolean
}

const peopleData: Readonly<Record<string, PeopleEntry>> = ${JSON.stringify(people, null, 2)}

export function resolvePersonClient(key: string): ResolvedPerson {
  const normalized = key.trim()
  const entry = peopleData[normalized]

  return entry
    ? {
        key: normalized,
        name: entry.name,
        description: entry.description ?? null,
        profile: entry.profile ?? null,
        email: entry.email ?? null,
        social: entry.social ?? {},
        isFallback: false,
      }
    : {
        key: normalized,
        name: normalized,
        description: null,
        profile: null,
        email: null,
        social: {},
        isFallback: true,
      }
}
`
}

function main(): void {
  const people = loadYaml<PeopleMap>(PEOPLE_PATH)
  if (!people || typeof people !== "object" || Array.isArray(people)) {
    process.stderr.write(`Error: could not parse ${PEOPLE_PATH}\n`)
    process.exit(1)
  }

  const autoAliases = loadYaml<AliasMap>(ALIASES_PATH)
  const overrideAliases = loadYaml<AliasMap>(ALIAS_OVERRIDES_PATH)
  const resolver = buildAliasResolver(autoAliases, overrideAliases)

  const profileMap: Record<string, string> = {}
  for (const peopleKey of Object.keys(people)) {
    profileMap[peopleKey] = resolver.get(peopleKey.toLowerCase()) ?? peopleKey
  }

  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf-8")) as Record<
    string,
    ArticleEntry
  >
  const excluded = new Set(["gtmc-bot"])
  for (const maintainer of loadYaml<string[]>(MAINTAINERS_PATH) ?? []) {
    excluded.add(maintainer.toLowerCase())
    excluded.add(
      (resolver.get(maintainer.toLowerCase()) ?? maintainer).toLowerCase()
    )
  }

  const authors = new Set<string>()
  for (const entry of Object.values(manifest)) {
    if (entry.isFolder) continue
    for (const handle of [entry.author, ...(entry.coAuthors ?? [])]) {
      if (!handle) continue
      const canonical = (
        resolver.get(handle.toLowerCase()) ?? handle
      ).toLowerCase()
      if (!excluded.has(canonical)) authors.add(canonical)
    }
  }

  const sorted: Record<string, string> = {}
  for (const key of Object.keys(profileMap).toSorted()) {
    sorted[key] = profileMap[key]
  }

  writeFileSync(PROFILES_JSON_PATH, `${JSON.stringify(sorted, null, 2)}\n`)
  writeFileSync(PROFILES_TS_PATH, renderAuthorProfiles(sorted, authors))
  writeFileSync(PEOPLE_TS_PATH, renderPeopleData(people))
  process.stdout.write(
    `Generated people artifacts for ${Object.keys(sorted).length} profiles\n`
  )
}

main()
